export enum AppResource {
  AUTH = 'AUTH',
  USER = 'USER',
  UPLOAD = 'UPLOAD',
  PERMISSION = 'PERMISSION',
  ROLE = 'ROLE',
  FACULTY = 'FACULTY',
  MAJOR = 'MAJOR',
  CLASS = 'CLASS',
}

export enum AppPermission {
  USER_VIEW = 'user:view',
  USER_CREATE = 'user:create',
  USER_UPDATE = 'user:update',
  USER_UPDATE_OWN = 'user:update_own',
  USER_DELETE = 'user:delete',
  UPLOAD_IMAGE = 'upload:image',
  UPLOAD_VIDEO = 'upload:video',
  PERMISSION_VIEW = 'permission:view',
  PERMISSION_CREATE = 'permission:create',
  PERMISSION_UPDATE = 'permission:update',
  PERMISSION_DELETE = 'permission:delete',
  ROLE_VIEW = 'role:view',
  ROLE_CREATE = 'role:create',
  ROLE_UPDATE = 'role:update',
  ROLE_DELETE = 'role:delete',
  FACULTY_VIEW = 'faculty:view',
  FACULTY_CREATE = 'faculty:create',
  FACULTY_UPDATE = 'faculty:update',
  FACULTY_DELETE = 'faculty:delete',
  MAJOR_VIEW = 'major:view',
  MAJOR_CREATE = 'major:create',
  MAJOR_UPDATE = 'major:update',
  MAJOR_DELETE = 'major:delete',
  CLASS_VIEW = 'class:view',
  CLASS_CREATE = 'class:create',
  CLASS_UPDATE = 'class:update',
  CLASS_DELETE = 'class:delete',
}
