name: TSP Nest Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd ~/teaching-support/tsp-nest
            git fetch origin
            git checkout main
            git pull
            yarn
            yarn build
            pm2 delete tsp-nest
            pm2 start dist/main.js --name tsp-nest
